//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitySetupApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MovieId { get; set; }
        public string MovieTitle { get; set; }
        public string Genre { get; set; }
        public string Year { get; set; }
        public Nullable<int> DirectorId { get; set; }
        public string Watched { get; set; }
    }
}
